---
- name: install postgres repo
  dnf:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    disable_gpg_check: yes
    state: latest

- name: disable the built-in PostgreSQL module
  command: 
    cmd: dnf -y module disable postgresql
    warn: false
  register: disablePostgresModuleResult
  changed_when:
  - '"Disabling modules" in disablePostgresModuleResult.stdout'

- name: install postgres
  dnf:
    name: postgresql13-server
    state: latest
