---
- name: install epel repo
  yum:
    name: epel-release
    state: present

- name: update yum cache and upgrade all packages
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: install common utilities (vim, tree, lsof, etc)
  yum:
    name: [ vim, tree, lsof ]
    state: latest

- include: ntp.yml
