---
- name: install epel repo
  dnf:
    name: epel-release
    state: present

- name: update dnf cache and upgrade all packages
  dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: install python3 devel, pip, tools, and libs packages
  dnf:
    name: [ python3-devel, python3-pip, python3-tools, python3-libs ]
    state: latest

- name: install common utilities (vim, tree, lsof, etc)
  dnf:
    name: [ vim, tree, lsof ]
    state: latest
