---
# tasks file for app
- name: check for virtualenv dir
  stat:
    path: "{{ venvPath }}"
  register: venvStatResult

- name: create virtualenv dir if necessary
  command:
    cmd: "python3 -m venv {{ venvPath }}"
  when: 'venvStatResult.stat.exists == 0'

- name: install git
  become: yes
  dnf:
    name: git
    state: latest

- name: clone axlist-app repo
  git:
    repo: "https://github.com/{{ githubUser }}/{{ githubProject }}"
    dest: /home/centos/axlist-app
    version: "{{ axlistVersion }}"

- name: install axlist-app dependencies
  pip:
    requirements: /home/centos/axlist-app/requirements.txt
    virtualenv: "{{ venvPath }}"

- name: install gunicorn
  pip:
    name: gunicorn
    virtualenv: "{{ venvPath }}"

- name: install axlist systemd service file
  become: yes
  template:
    src: axlist-app.service.j2
    dest: /etc/systemd/system/axlist-app.service
    owner: centos
    group: centos
    mode: '0644'

- name: fetch systemd service file test
  fetch:
    src: /etc/systemd/system/axlist-app.service
    dest: "axlist_dump/{{inventory_hostname}}"

- name: initialize axlist database
  shell:
    cmd: "FLASK_APP={{ flaskApp }} FLASK_ENV={{ flaskEnv }} {{ venvPath }}/bin/flask init-db"
    chdir: /home/centos/axlist-app

- name: Enable and start axlist service
  become: yes
  service:
    name: axlist-app
    state: started
    enabled: yes
