---
plugin: aws_ec2
boto_profile: default

regions:
  - us-west-2

ansible_user: centos
ansible_ssh_private_key_file: ~/.ssh/20201113_auxcord-python-server.key

hostnames:
  # - tag:Name=auxcord
  - ip-address

keyed_groups:
  - key: tags
    prefix: tag
  - key: instance_type
    prefix: instance_type
  - key: placement.region
    prefix: aws_region
