---
- name: apply common configuration to auxcord host
  hosts: all
  become: yes

  roles:
  - common

- name: apply nginx configuration to loadbalancer host
  hosts: tag_Name_auxcord_lb
  become: yes

  roles:
  - loadbalancer

- name: apply db configuration to db host
  hosts: tag_Name_auxcord_db
  become: yes

  roles:
  - database

- name: apply app configuration to app host
  hosts: tag_Name_auxcord_app
  become: yes

  roles:
  - app
