---
- name: bootstrap hosts to use python3 and dnf
  hosts: all
  become: yes
  gather_facts: false

  roles:
  - bootstrap

- name: apply common configuration to axlist host
  hosts: all
  become: yes

  roles:
  - common

- name: apply db configuration to db host
  hosts: tag_Name_axlist_db
  become: yes

  roles:
  - database

- name: apply app configuration to app host
  hosts: tag_Name_axlist_app

  roles:
  - app

- name: apply nginx configuration to loadbalancer host
  hosts: tag_Name_axlist_lb
  become: yes

  roles:
  - loadbalancer
